### ISSUE TITLE
Failed to start dnsmasq

### ISSUE THREAD

**Issue by heinzmarchl** [moodlebox/moodlebox#187] opened 2020-11-01 15:56 UTC
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### To Reproduce
Complete and precise steps to reproduce the behavior:

## Additional context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
- Raspberry Pi model [e.g. RPi 3B+]
- MoodleBox version
- MoodleBox plugin version

**Comment by martignoni** [comment] 2020-11-01 17:37
Please complete the form. Without more info, impossible to fix anything.

**Comment by martignoni** [comment] 2020-11-12 15:38
Will be closed in a few days when no details given.

**Comment by heinzmarchl** [comment] 2020-11-12 17:28
rassberry pi 4 8GB
startscreen
Problem to connect with moodlebox from another computer(windows10, and ipad
lan connection ok.
failed  failed to start dnsmasq - a lightweight DHCP and caching DNS server
orginal Netzteil 
![start moodlebox tty1 failed](https://user-images.githubusercontent.com/50845358/98974032-bae3d880-2514-11eb-9b12-fe967716b3a6.jpg)
what can I do?
mfg
Heinz Marchl

**Comment by martignoni** [comment] 2020-11-12 17:42
Impossible to know without more context.

To be able to investigate, we need **precise instructions** on how to reproduce the issue, which are still missing. More over, RPi model, MoodleBox image version, etc. must be given.

Please complete the above form, specially the _To reproduce_ section with precise steps and the _Additional context_ section, and, if applicable, what actions you made before the problem occured. Only with such info can we investigate if there's really an issue and try to fix it.

**Comment by martignoni** [comment] 2020-11-12 18:39
Or maybe is this no bug and you just need support? In this case, you're welcome on the [MoodleBox discussion forum](https://discuss.moodlebox.net/).

**Comment by martignoni** [comment] 2020-12-05 14:37
Closing, not a bug.

**Closed by martignoni** 2020-12-05 14:37 UTC
Labels: Type: invalid
